services:
  booksservice:
    build:
      context: ./BenjaminJeran/Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - ./books.db:/usr/src/app/books.db
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  userservice:
    build:
      context: ./AlenSaruga/user-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  inventoryservice:
    build:
      context: ./AlenSaruga/inventory-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002" 
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  frontendservice: 
    build:
      context: ./BenjaminJeran/SOA_Bookcase_Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  reviewservice: 
    build:
      context: ./mihaklancnik/reviews/reviews_api
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  orderservice: 
    build:
      context: ./mihaklancnik/order_api
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
