services:
  booksservice:
    build:
      context: ./BenjaminJeran/Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network

  userservice:
    build:
      context: ./AlenSaruga/user-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    networks:
      - app-network

  inventoryservice:
    build:
      context: ./AlenSaruga/inventory-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002" 
    networks:
      - app-network

  frontendservice: 
    build:
      context: ./BenjaminJeran/SOA_Bookcase_Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  reviewservice: 
    build:
      context: ./mihaklancnik/reviews/reviews-api
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    networks:
      - app-network

  orderservice: 
    build:
      context: ./mihaklancnik/order-api
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    networks:
      - app-network


  

networks:
  app-network:
    driver: bridge
